service: 
  name: consorciei
package:
  individually: true
  exclude:
    - ./**

frameworkVersion: ">=1.0.0 <2.0.0"

provider:
  name: aws
  region: us-east-2
  runtime: nodejs10.x
  tags:
    projeto: consorciei
  stage: ${opt:stage, 'dev'}
  memorySize: 128
  versionFunctions: false
  deploymentBucket:
    name: consorciei-lambdas

functions:
  authMiddleware:
    handler: authMiddleware/index.handler
    name: ${self:provider.stage}-${self:service.name}-authMiddleware
    description: Request middleware authorizer
    timeout: 30
    package:
      include:
        - authMiddleware/**
